### ISSUE TITLE
Error on self-signed certificates

### ISSUE THREAD

**Issue by OverkillSD** [brz/Breez-ClickOnce#2]
I get the following error when trying to open a remote console in HP's iLO for managing a server; this error does not happen in IE at all. Is this something that can be corrected within the addon/helper?

PLATFORM VERSION INFO
	Windows 			: 10.0.19042.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4300.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: https://192.168.1.20/html/IRC.application?addr=192.168.1.20&sessionKey=8175aa105a4ec0b2ccc339e29dce0097&lang=en&port=443&alt_mode=0&cofc_goback=false

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://192.168.1.20/html/IRC.application?addr=192.168.1.20&sessionKey=8175aa105a4ec0b2ccc339e29dce0097&lang=en&port=443&alt_mode=0&cofc_goback=false resulted in exception. Following failure messages were detected:
		+ Downloading https://192.168.1.20/html/IRC.application?addr=192.168.1.20&sessionKey=8175aa105a4ec0b2ccc339e29dce0097&lang=en&port=443&alt_mode=0&cofc_goback=false did not succeed.
		+ The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
		+ The remote certificate is invalid according to the validation procedure.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [2/23/2021 5:07:52 PM] : Activation of https://192.168.1.20/html/IRC.application?addr=192.168.1.20&sessionKey=8175aa105a4ec0b2ccc339e29dce0097&lang=en&port=443&alt_mode=0&cofc_goback=false has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2/23/2021 5:07:52 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading https://192.168.1.20/html/IRC.application?addr=192.168.1.20&sessionKey=8175aa105a4ec0b2ccc339e29dce0097&lang=en&port=443&alt_mode=0&cofc_goback=false did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Security.Authentication.AuthenticationException
		- The remote certificate is invalid according to the validation procedure.
		- Source: System
		- Stack trace:
			at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
			at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
			at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
			at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
			at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
			at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
			at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
			at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
			at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
			at System.Net.ConnectStream.WriteHeaders(Boolean async)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by brz** [comment]
Have you tried putting the selfsigned certificate in the trust chain of the machine trying to open the clickonce url? The problem probably doesn't occur in IE because you have explicitly accepted the SSL certificate as being valid there (overriding the security warnings).
Also I think it would be better using a qualified hostname instead of IP address and assigning a proper SSL certificate instead of a selfsigned (using a CA server for example)

**Comment by brz** [comment]
Closing issue as no response received.
